name: chess
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  chess_os:
    path: os
  flutter_svg: ^2.0.7
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  args: ^2.4.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pieces/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: inter_bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: inter_extra_bold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

    - family: inter_light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf

    - family: inter_medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: inter_semibold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
